const LLM_ERROR_CODES = {
  DISABLED: 'LLM_DISABLED',
  NOT_CONFIGURED: 'LLM_NOT_CONFIGURED',
  PROVIDER_ERROR: 'LLM_PROVIDER_ERROR',
  TIMEOUT: 'LLM_TIMEOUT',
  RESPONSE_INVALID: 'LLM_RESPONSE_INVALID'
};

const LLM_TASKS = {
  PROGRESS_WORDING: 'progress_wording',
  FINAL_SUMMARY: 'final_summary',
  REASK: 'reask'
};

module.exports = {
  LLM_ERROR_CODES,
  LLM_TASKS
};
