const MESSAGE_TYPES = {
  ERROR: 'ERROR',
  JOB_EVENT: 'JOB_EVENT',
  JOB_HEARTBEAT: 'JOB_HEARTBEAT',
  SNAPSHOT: 'SNAPSHOT',
  SUBSCRIBED: 'SUBSCRIBED',
  UNSUBSCRIBED: 'UNSUBSCRIBED'
};

const JOB_EVENTS = {
  JOB_QUEUED: 'JOB_QUEUED',
  VALIDATION_STARTED: 'VALIDATION_STARTED',
  VALIDATION_COMPLETED: 'VALIDATION_COMPLETED',
  FILTERING_STARTED: 'FILTERING_STARTED',
  FILTERING_COMPLETED: 'FILTERING_COMPLETED',
  ASSET_LOADING_STARTED: 'ASSET_LOADING_STARTED',
  ASSET_LOADING_COMPLETED: 'ASSET_LOADING_COMPLETED',
  GENERATION_STARTED: 'GENERATION_STARTED',
  GENERATION_COMPLETED: 'GENERATION_COMPLETED',
  OUTPUT_COLLECTION_STARTED: 'OUTPUT_COLLECTION_STARTED',
  OUTPUT_COLLECTION_COMPLETED: 'OUTPUT_COLLECTION_COMPLETED',
  EXPORT_STARTED: 'EXPORT_STARTED',
  JOB_COMPLETED: 'JOB_COMPLETED',
  JOB_FAILED: 'JOB_FAILED',
  JOB_CANCELLED: 'JOB_CANCELLED'
};

const TERMINAL_JOB_STATUSES = new Set([
  'completed',
  'completed_with_warning',
  'failed',
  'cancelled',
  'cancelled_with_partial_result'
]);

const TERMINAL_PHASES = new Set([
  'COMPLETED',
  'FAILED',
  'CANCELLED'
]);

module.exports = {
  JOB_EVENTS,
  MESSAGE_TYPES,
  TERMINAL_JOB_STATUSES,
  TERMINAL_PHASES
};
