const { WORKER_DISPLAY_NAMES, WORKER_IDS } = require('../workerTypes');

module.exports = {
  workerId: WORKER_IDS.MW_PR,
  displayName: WORKER_DISPLAY_NAMES[WORKER_IDS.MW_PR],
  engineRepository: 'Gumb-D/create-pr-cd',
  engineVersion: 'approved-98412d7',
  engineCommit: '98412d7ecab8e1ba6c53e170f3ffea30b75b3443',
  runtimeFingerprint: '560134a769911835b51df503dc95e32854eb2e495c48d14102376e877ee53d6e',
  runtimeFiles: [
    'Info/input/contract_info_reference.md',
    'Info/input/ecc_template.xls',
    'Info/input/pr_model.xlsx',
    'Info/reference/geography_mapping.json',
    'Info/reference/sabah_sarawak_adm2.geojson',
    'config/du_profiles/cd_consolidation_2023_decom_pr_v1.yaml',
    'config/du_profiles/cd_consolidation_2023_rollout_pr_v1.yaml',
    'config/du_profiles/celcomdigi_bau_2023_pr_v1.yaml',
    'config/du_profiles/celcomdigi_bau_2024_pr_v1.yaml',
    'config/du_profiles/celcomdigi_usp_pr_v1.yaml',
    'config/du_profiles/jendela_tx_migration_pr_v1.yaml',
    'config/du_profiles/mw_eos_swap_pr_v1.yaml',
    'config/du_profiles/tx_mini_pr_v1.yaml',
    'config/du_profiles/tx_rollout_2023_pr_v1.yaml',
    'config/du_profiles/zte_tx_mini_pr_v1.yaml',
    'config/registries/canonical_sow_registry.yaml',
    'config/registries/mw_du_profile_identity_registry.yaml',
    'scripts/canonical_input_pipeline.py',
    'scripts/canonical_site_validator.py',
    'scripts/create_pr.py',
    'scripts/du_export_adapter.py',
    'scripts/du_profile_loader.py',
    'scripts/du_profile_resolver.py',
    'scripts/generate_tss_pr_ecc.py',
    'scripts/geography_resolver.py',
    'scripts/pr_helpers.py',
    'scripts/profile_du_export.py',
    'scripts/sow_normalization.py'
  ],
  inputs: ['prevalidated-export', 'generation-scope', 'site-codes', 'pr-scope'],
  outputs: ['ecc-output', 'warning-report', 'review-required-report', 'zip-package'],
  capabilities: ['site-filtering', 'tss', 'ti'],
  limitations: [],
  compatibilityStatus: 'verified'
};
