const { WORKER_DISPLAY_NAMES, WORKER_IDS } = require('../workerTypes');

module.exports = {
  workerId: WORKER_IDS.MW_PR,
  displayName: WORKER_DISPLAY_NAMES[WORKER_IDS.MW_PR],
  engineRepository: 'Gumb-D/create-pr-cd',
  engineVersion: 'approved-237cf60',
  engineCommit: '237cf6057f37587208a7fcdf497fa9097c0bf95d',
  runtimeFingerprint: '758178afe4580a6d9d1b22f654071a810b9bccb1319caaa1e0a9fbf5d2fe83f9',
  runtimeFiles: [
    'Info/input/contract_info_reference.md',
    'Info/input/ecc_template.xls',
    'Info/input/pr_model.xlsx',
    'Info/reference/geography_mapping.json',
    'Info/reference/sabah_sarawak_adm2.geojson',
    'config/du_profiles/celcomdigi_cd_consolidation_2023_pr_v1.yaml',
    'config/du_profiles/celcomdigi_bau_2023_pr_v1.yaml',
    'config/du_profiles/celcomdigi_bau_2024_pr_v1.yaml',
    'config/du_profiles/celcomdigi_usp_pr_v1.yaml',
    'config/du_profiles/jendela_tx_migration_pr_v1.yaml',
    'config/du_profiles/mw_eos_swap_pr_v1.yaml',
    'config/du_profiles/tx_mini_pr_v1.yaml',
    'config/du_profiles/tx_rollout_2023_pr_v1.yaml',
    'config/du_profiles/zte_tx_mini_pr_v1.yaml',
    'config/registries/canonical_sow_registry.yaml',
    'config/registries/mw_du_profile_identity_registry.yaml',
    'config/subcontractor_pr_policy.json',
    'scripts/canonical_input_pipeline.py',
    'scripts/canonical_site_validator.py',
    'scripts/create_pr.py',
    'scripts/create_pr_impl.py',
    'scripts/du_export_adapter.py',
    'scripts/du_profile_loader.py',
    'scripts/du_profile_resolver.py',
    'scripts/generate_tss_pr_ecc.py',
    'scripts/geography_resolver.py',
    'scripts/iepms_export_source_resolver.py',
    'scripts/jendela_migration_decision.py',
    'scripts/pr_helpers.py',
    'scripts/pr_safety_controls.py',
    'scripts/profile_du_export.py',
    'scripts/sow_normalization.py'
  ],
  inputs: ['prevalidated-export', 'generation-scope', 'site-codes', 'pr-scope'],
  outputs: ['ecc-output', 'warning-report', 'review-required-report', 'zip-package'],
  capabilities: ['site-filtering', 'tss', 'ti'],
  limitations: [],
  compatibilityStatus: 'verified'
};
